### ISSUE TITLE
create a light/dark mode

### ISSUE THREAD

**Issue by Rs-py** [Rs-py/tesla#1]
Create a light/dark mode button and a light version of the ejs file.

**Comment by Thilagavathi1** [comment]
@Rs-py i would like to work on this issue.could u please assign it to me

**Comment by Rs-py** [comment]
> @Rs-py i would like to work on this issue.could u please assign it to me

Of course! Just did ✅

**Comment by Thilagavathi1** [comment]
@Rs-py please review this [PR](https://github.com/Rs-py/tesla/pull/5) and merge it
