### ISSUE TITLE
create a new feature

### ISSUE THREAD

**Issue by Rs-py** [Rs-py/tesla#3]

**Comment by eshaiyer** [comment]
A new feature consisting of a website which calculates the amount of petrol consumed by our combustion engine vehicle and compares it to the consumption of electricity by a Tesla vehicle and basically compares the two. This will help the users understand why the Tesla vehicle is more economical and cost efficient when in comparison to a combustion engine vehicle which uses enormous amount of petrol/diesel/gas.

This is the javascript code for the same -
const readline = require('readline');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question("Enter the cost of petrol per liter (or gallon): ", function(cost_of_petrol) {
  rl.question("Enter the total distance of the journey in kilometers (or miles): ", function(total_distance) {
    rl.question("Enter the fuel efficiency of your vehicle in liters per kilometer (or gallons per mile): ", function(fuel_efficiency) {
      cost_of_petrol = parseFloat(cost_of_petrol);
      total_distance = parseFloat(total_distance);
      fuel_efficiency = parseFloat(fuel_efficiency);

      // Calculate the amount of petrol consumed
      const petrol_consumed = total_distance / fuel_efficiency;

      // Calculate the total cost of petrol for the journey
      const total_cost = petrol_consumed * cost_of_petrol;

      // Display the results
      console.log(`Petrol consumed for the journey: ${petrol_consumed.toFixed(2)} liters (or gallons)`);
      console.log(`Total cost of petrol for the journey: $${total_cost.toFixed(2)}`);

      rl.close();
    });
  });
});
https://github.com/eshaiyer/tesla/blob/main/petrolconsumed.js

**Comment by eshaiyer** [comment]
Hi @Rs-py ,
I am pretty new to the world of Open Source so I don't really know what happens when an issue is assigned to me. Can you just give me an overview about what I am supposed to do?

**Comment by Rs-py** [comment]
Hey friend. Good work! Sorry I haven’t been reading my emails. You have to do a pull request now to the main github which will “merge” the code. Here’s a guide here! You can also look it up on youtube too! https://opensource.com/article/19/7/create-pull-request-github

On Oct 31, 2023, at 4:01 PM, Esha J A Iyer ***@***.***> wrote:

﻿

Hi @Rs-py<https://github.com/Rs-py> ,
I am pretty new to the world of Open Source so I don't really know what happens when an issue is assigned to me. Can you just give me an overview about what I am supposed to do?

**Comment by eshaiyer** [comment]
Ah okay peace got it. Thank you so much ! You've been really helpful!
